# Generated by Django 2.2 on 2020-02-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20200211_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Service provider', 'Service provider')], default='Customer', max_length=100),
        ),
    ]
